version: '3.8'
services:
  web:
    image: kaiwalyakoparkar/podlogger-web
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    networks:
      - app-network

  api:
    image: kaiwalyakoparkar/podlogger-api
    container_name: api
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
