---
name: build and push api docker image
on:
  push

jobs:
  release-docker:
    name: Release docker image
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          tags: |
            type=sha, prefix=v1-
          images: kaiwalyakoparkar/podlogger-api
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kaiwalyakoparkar/podlogger-api
          tag_with_ref: true
          add_git_labels: true
          tag_with_sha: true
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./api/
          tags: ${{ steps.meta.outputs.tags }},latest
          labels: ${{ steps.meta.outputs.labels }}
          push: true