apiVersion: v1
kind: Pod
metadata:
  name: podlogger
  labels:
    app: podlogger
spec:
  containers:
    - name: web
      image: kaiwalyakoparkar/podlogger-web
      ports:
      - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"
    - name: api
      image: kaiwalyakoparkar/podlogger-api
      envFrom:
      - configMapRef:
          name: logger-config
      ports:
      - containerPort: 8080
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: podlogger-svc
spec:
  type: NodePort
  selector:
    app: podlogger
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
